import { expect, test, describe } from "bun:test";
import { runEngine, loadEnvVariables } from '../Engine/utils/test_utils.js';

// Auto-generated by autoRecipe.js (--url-only)
await loadEnvVariables();
const TIMEOUT = parseInt(process.env.TEST_TIMEOUT);

const RECIPE = "amazoncom.json";
const INPUT_URL = "https://www.amazon.com/MineCozy-Indoor-Cushions-Dining-Tufted/dp/B0GJ5W8GM8\\?sr\\=8-1";

describe(RECIPE, () => {
    test("--type url", async () => {
        const result = await runEngine(`generic/${RECIPE}`, "url", INPUT_URL);

        expect(result.TITLE).toBeDefined();
        expect(result.DESCRIPTION).toBeDefined();
        expect(result.COVER).toBeDefined();
    }, TIMEOUT);
});
