import { expect, test, describe } from "bun:test";
import { runEngine, findEntry, loadEnvVariables } from '../Engine/utils/test_utils.js';

// Auto-generated by autoRecipe.js
await loadEnvVariables();
const TIMEOUT = parseInt(process.env.TEST_TIMEOUT);

const RECIPE = "distillercom.json";
const INPUT = {
    AUTOCOMPLETE: "bourbon",
    URL: "https://distiller.com/spirits/buffalo-trace-bourbon"
};

const ENTRY = {"TITLE":"Buffalo Trace Bourbon","SUBTITLE":""};

describe(RECIPE, () => {
    test("--type autocomplete", async () => {
        const results = await runEngine(`generic/${RECIPE}`, "autocomplete", INPUT.AUTOCOMPLETE);
        
        const entry = findEntry(results, ENTRY.TITLE);

        expect(entry.TITLE).toBe(ENTRY.TITLE);
        
        expect(entry.URL).toBeDefined();
        expect(entry.COVER).toBeDefined();
    }, TIMEOUT);

    test("--type url", async () => {
        const result = await runEngine(`generic/${RECIPE}`, "url", INPUT.URL);

        expect(result.TITLE).toBeDefined();
        expect(result.DESCRIPTION).toBeDefined();
        expect(result.COVER).toBeDefined();
    }, TIMEOUT);
});
