import { expect, test, describe } from "bun:test";
import { runEngine, findEntry, loadEnvVariables } from '../Engine/utils/test_utils.js';

// Auto-generated by autoRecipe.js
await loadEnvVariables();
const TIMEOUT = parseInt(process.env.TEST_TIMEOUT);

const RECIPE = "fragranticacom.json";
const INPUT = {
    AUTOCOMPLETE: "Chanel",
    URL: "https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-Eau-de-Parfum-40069.html"
};

const ENTRY = {"TITLE":"Chanel No 5 Eau de Parfum","SUBTITLE":"Chanel"};

describe(RECIPE, () => {
    test("--type autocomplete", async () => {
        const results = await runEngine(`generated/${RECIPE}`, "autocomplete", INPUT.AUTOCOMPLETE);
        
        const entry = findEntry(results, ENTRY.TITLE, ENTRY.SUBTITLE);

        expect(entry.TITLE).toBe(ENTRY.TITLE);
        expect(entry.SUBTITLE).toBe(ENTRY.SUBTITLE);
        expect(entry.URL).toBeDefined();
        expect(entry.COVER).toBeDefined();
    }, TIMEOUT);

    test("--type url", async () => {
        const result = await runEngine(`generated/${RECIPE}`, "url", INPUT.URL);

        expect(result.TITLE).toBeDefined();
        expect(result.DESCRIPTION).toBeDefined();
        expect(result.COVER).toBeDefined();
    }, TIMEOUT);
});
