import { expect, test, describe } from "bun:test";
import { runEngine, loadEnvVariables } from '../Engine/utils/test_utils.js';

// Auto-generated by autoRecipe.js
await loadEnvVariables();
const TIMEOUT = parseInt(process.env.TEST_TIMEOUT);

const RECIPE = "fragranticacom.json";
const INPUT = {
    URL: "https://www.fragrantica.com/perfume/Chanel/Chanel-No-5-Eau-de-Parfum-40069.html"
};

describe(RECIPE, () => {
    test("--type url", async () => {
        const result = await runEngine(`generic/${RECIPE}`, "url", INPUT.URL);

        expect(result.TITLE).toBeDefined();
        expect(result.DESCRIPTION).toBeDefined();
        expect(result.COVER).toBeDefined();
    }, TIMEOUT);
});
