import { expect, test, describe } from "bun:test";
import { runEngine, loadEnvVariables } from '../Engine/utils/test_utils.js';

// Auto-generated by autoRecipe.js
await loadEnvVariables();
const TIMEOUT = parseInt(process.env.TEST_TIMEOUT);

const RECIPE = "funkocom.json";
const INPUT = {
    AUTOCOMPLETE: "Dragon Ball",
    URL: "https://funko.com/pop-super-saiyan-trunks/91825.html"
};

describe(RECIPE, () => {
    test("--type autocomplete", async () => {
        const results = await runEngine(`generic/${RECIPE}`, "autocomplete", INPUT.AUTOCOMPLETE);

        expect(results.length).toBeGreaterThan(0);

        for (const entry of results) {
            expect(entry.TITLE).not.toBeEmpty();
            expect(entry.URL).toMatch(/^https:\/\/funko\.com\/.+\.html$/);
            expect(entry.COVER).not.toBeEmpty();
        }

        expect(results.some(entry => /dragon ball|dbz/i.test(entry.TITLE) || /dragon-ball|dbz/i.test(entry.URL))).toBe(true);
    }, TIMEOUT);

    test("--type url", async () => {
        const result = await runEngine(`generic/${RECIPE}`, "url", INPUT.URL);

        expect(result.TITLE).toBeDefined();
        expect(result.DESCRIPTION).toBeDefined();
        expect(result.COVER).toBeDefined();
    }, TIMEOUT);
});
